# ------------------------------------ #
#       NamLivechat Configuration      #
# ------------------------------------ #

# ใส่ YouTube Data API v3 Key ของคุณที่นี่
# ไปที่ https://console.cloud.google.com/ เพื่อสร้างคีย์
youtube-api-key: "YOUR_API_KEY_HERE"

# รูปแบบข้อความแชทธรรมดาที่จะแสดงในเกม
# %player% = ชื่อผู้ใช้ YouTube (พร้อมสีตามยศ)
# %message% = ข้อความ
message-format: "&c[YouTube] &f%player% : &e%message%"

# ตั้งค่าสีสำหรับยศต่างๆ ในแชท YouTube
role-colors:
  owner: "&6"      # สีทองสำหรับเจ้าของช่อง
  moderator: "&9"  # สีฟ้าสำหรับผู้ดูแล
  member: "&a"     # สีเขียวสำหรับสมาชิก (Sponsor)
  default: "&7"    # สีขาวสำหรับผู้ชมทั่วไป

# ========================================= #
#         YouTube Alert Settings            #
# ========================================= #
youtube-alerts:
  # ตั้งค่าเป็น true เพื่อเปิดการแจ้งเตือน Super Chat
  show-super-chat: true
  # ตั้งค่าเป็น true เพื่อเปิดการแจ้งเตือนเมื่อมีคนสมัครสมาชิกใหม่
  show-new-members: true

# รูปแบบข้อความแจ้งเตือน
# %player% = ชื่อคนที่โดเนท/สมัคร
# %amount% = จำนวนเงินที่โดเนท (สำหรับ Super Chat)
# %message% = ข้อความที่แนบมากับ Super Chat
super-chat-format: "&6[Super Chat] &e%player% &fhas donated &a%amount%&f: &d%message%"
new-member-format: "&b[New Member] &d%player% &ahas just subscribed!"

# ========================================= #
#            Sound Settings                 #
# ========================================= #
# สามารถหาชื่อเสียงทั้งหมดได้ที่: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sounds:
  super-chat:
    # เสียงเมื่อมี Super Chat เข้ามา
    name: "ENTITY_FIREWORK_ROCKET_LARGE_BLAST"
    volume: 1.0  # ความดัง (แนะนำ 0.5 - 2.0)
    pitch: 1.2   # ระดับเสียง (แนะนำ 0.5 - 2.0)
  new-member:
    # เสียงเมื่อมีคนสมัครสมาชิกใหม่
    name: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.5

# ========================================= #
#          Boss Bar Alert Settings          #
# ========================================= #
# BarColor options: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
# BarStyle options: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
bossbar-alerts:
  enabled: true
  duration-seconds: 10
  super-chat:
    color: "YELLOW"
    style: "SOLID"
  new-member:
    color: "PINK"
    style: "SOLID"