# ================================================== #
#         NamLivechat TikTok Configuration           #
# ================================================== #

# เปิด/ปิด การใช้งานส่วนของ TikTok
enabled: true

# รูปแบบข้อความแชทธรรมดาที่จะแสดงในเกม
# %user% = ชื่อผู้ใช้ TikTok
# %message% = ข้อความ
message-format: "&b[TikTok] &f%user%&7 : &f%message%"

# ================================================== #
#                 TikTok Event Alerts                #
# ================================================== #
events:
  # เปิด/ปิด การแสดงผลการแจ้งเตือนทั้งหมดในส่วนนี้
  enabled: true

  # --- การส่งของขวัญ (Gifts) ---
  gift:
    enabled: true
    # %user% = ชื่อผู้ใช้ที่ส่งของขวัญ
    # %gift_name% = ชื่อของขวัญ
    # %amount% = จำนวนของขวัญที่ส่ง
    # %total_value% = มูลค่ารวมของเพชร (Diamonds)
    message: "&e[TikTok Gift] &f%user% &ahas sent %amount%x &d%gift_name% &a(Value: %total_value% Diamonds)!"
    sound:
      name: "entity.villager.celebrate"
      volume: 1.0
      pitch: 1.0
    boss-bar:
      enabled: true
      message: "&e&l%user% &f&lsent a &d&l%gift_name%&f&l!"
      color: "YELLOW"
      duration: 10

  # --- การกดติดตาม (Follow) ---
  follow:
    enabled: true
    # %user% = ชื่อผู้ใช้ที่กดติดตาม
    message: "&b[TikTok] &f%user% &ehas followed the stream!"
    sound:
      name: "entity.player.levelup"
      volume: 1.0
      pitch: 1.5
    boss-bar:
      enabled: true
      message: "&b&lNew Follower: &f&l%user%"
      color: "BLUE"
      duration: 8