name: NamLivechat
version: '1.0'
main: com.namLivechat.NamLivechat
api-version: '1.21'
folia-supported: true
author: Nattapat2871
description: Displays YouTube live chat in Minecraft.
commands:
  livechat:
    description: Connects to a YouTube live stream.
    usage: /<command> <start|stop> <youtube|tiktok|twitch>
  namlivechat:
    description: Admin commands for NamLivechat.
    usage: /<command> [reload]
    permission: namlivechat.admin
permissions:
  namlivechat.admin:
    description: Allows access to admin commands for NamLivechat.
    default: op