# ================================================== #
#         NamLivechat TikTok Configuration           #
# ================================================== #

enabled: true

# %user%, %message%
message-format: "&8[&bTi&fkT&cok&8] &9%user% &7 : &a%message%"

# --- NEW: Role Colors ---
# Configure role colors for TikTok users
role-colors:
  moderator: "&9"      # Blue for moderators
  subscriber: "&a"   # Green for subscribers
  gifter: "&6"       # Gold for gifters
  default: "&7"      # Gray for general viewers

# ================================================== #
#                 TikTok Event Alerts                #
# ================================================== #
events:
  enabled: true

  # --- Gifts ---
  gift:
    enabled: true
    # %user%, %gift_name%, %amount%, %total_value%
    message: "&8[&bTi&fkT&cok &eGift&7] &f%user% &ahas sent %amount%x &d%gift_name% &a(Value: %total_value% Diamonds)!"
    sound:
      name: "entity.villager.celebrate"
      volume: 1.0
      pitch: 1.0
    boss-bar:
      enabled: true
      message: "&e&l%user% &f&lsent a &d&l%gift_name%&f&l!"
      color: "YELLOW"
      duration: 10

  # --- Follow ---
  follow:
    enabled: true
    # %user%
    message: "&8[&bTi&fkT&cok&8] &f%user% &ehas followed the stream!"
    sound:
      name: "entity.player.levelup"
      volume: 1.0
      pitch: 1.5
    boss-bar:
      enabled: true
      message: "&8[&bTi&fkT&cok&8] &b&lNew Follower: &f&l%user%"
      color: "BLUE"
      duration: 8