# ================================================== #
#         NamLivechat Twitch Configuration           #
# ================================================== #

# Enable/disable the Twitch integration
enabled: true

# Access Token from https://twitchtokengenerator.com/
oauth-token: "YOUR_OAUTH_TOKEN_HERE"

# --- Formatting ---
# %user% = Twitch username (with color from role-colors)
# %message% = The message
format: "&5[Twitch] %user%&7 : &f%message%"

# --- Role Colors ---
# Configure role colors for Twitch users
role-colors:
  broadcaster: "&6"
  moderator: "&9"
  subscriber: "&a"
  vip: "&d"
  default: "&7"

# ================================================== #
#                Twitch Event Alerts                 #
# ================================================== #
events:
  # Enable/disable all event alerts in this section
  enabled: true

  # --- New Follower ---
  new-follower:
    enabled: true
    # %user% = Username of the new follower
    message: "&5[Twitch] &f%user% &ehas just followed!"
    sound:
      name: "entity.experience_orb.pickup"
      volume: 1.0
      pitch: 1.8
    boss-bar:
      enabled: true
      # %user%
      message: "&5[Twitch] &d&lNew Follower: &f&l%user%"
      color: "PURPLE"
      duration: 8

  # --- New Subscription ---
  new-subscription:
    enabled: true
    # %user%, %tier%
    message: "&d[Twitch] &f%user% &ehas just subscribed at Tier %tier%!"
    sound:
      name: "entity.player.levelup"
      volume: 1.0
      pitch: 1.2
    # --- NEW: Boss Bar Settings ---
    boss-bar:
      enabled: true
      # %user%, %tier%
      message: "&5[Twitch] &d&l%user% &f&lhas just subscribed! (Tier %tier%)"
      # Boss Bar colors: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      color: "PINK"
      # Display duration (seconds)
      duration: 10

  # --- Re-subscription ---
  resubscription:
    enabled: true
    # %user%, %months%, %streak%, %tier%
    message: "&d[Twitch] &f%user% &ehas resubscribed for %months% months! (Currently on a %streak% month streak!)"
    sound:
      name: "entity.player.levelup"
      volume: 1.0
      pitch: 1.5
    # --- NEW: Boss Bar Settings ---
    boss-bar:
      enabled: true
      # %user%, %months%, %streak%, %tier%
      message: "&5[Twitch] &a&l%user% &f&lresubscribed for %months% months! (%streak% month streak!)"
      color: "GREEN"
      duration: 12

  # --- Gift Subscription ---
  gift-subscription:
    enabled: true
    # %gifter%, %recipient%, %tier%
    message: "&d[Twitch] &f%gifter% &ehas gifted a Tier %tier% sub to &f%recipient%&e!"
    sound:
      name: "entity.villager.celebrate"
      volume: 1.0
      pitch: 1.0
    # --- NEW: Boss Bar Settings ---
    boss-bar:
      enabled: true
      # %gifter%, %recipient%, %tier%
      message: "&5[Twitch] &e&l%gifter% &f&lhas gifted a sub to &b&l%recipient%&f&l!"
      color: "YELLOW"
      duration: 10

  # --- Community Gift / Sub Bomb ---
  community-subscription:
    enabled: true
    # %gifter%, %count%, %tier%
    message: "&d[Twitch] &f%gifter% &eis gifting %count% Tier %tier% subs to the community!"
    sound:
      name: "entity.firework_rocket.large_blast"
      volume: 1.0
      pitch: 1.0
    # --- NEW: Boss Bar Settings ---
    boss-bar:
      enabled: true
      # %gifter%, %count%, %tier%
      message: "&5[Twitch] &b&lSUB BOMB! &f&l%gifter% is gifting &d&l%count% &f&lsubs!"
      color: "BLUE"
      duration: 15