# ================================================== #
#        NamLivechat YouTube Configuration           #
# ================================================== #

# Set to true to enable the YouTube integration.
enabled: true

# Enter your YouTube Data API v3 Key here
# Go to https://console.cloud.google.com/ to create a key
youtube-api-key: "YOUR_API_KEY_HERE"

# Format for regular chat messages displayed in-game
# %player% = YouTube username (with color based on role)
# %message% = The message
message-format: "&c[YouTube] &f%player%&7 : &e%message%"

# Configure colors for different roles in YouTube chat
role-colors:
  owner: "&6"      # Gold for the channel owner
  moderator: "&9"  # Blue for moderators
  member: "&a"     # Green for members (Sponsors)
  default: "&7"    # White for general viewers

# ================================================== #
#               YouTube Event Alerts                 #
# ================================================== #
youtube-alerts:
  # Set to true to enable Super Chat notifications
  show-super-chat: true
  # Set to true to enable new member notifications
  show-new-members: true

# --- Super Chat ---
super-chat:
  # %player%, %amount%, %message%
  message: "&c[YouTube] &e%player% &fhas Super Chat donated &a%amount%&f : &d%message%"
  sound:
    name: "entity.firework_rocket.large_blast"
    volume: 1.0
    pitch: 1.2
  # --- NEW: Boss Bar Settings ---
  boss-bar:
    enabled: true
    # %player%, %amount%, %message%
    message: "&c[YouTube] &e&l%player% &f&ldonated &a&l%amount%&f&l!"
    color: "YELLOW"
    duration: 12

# --- New Member ---
new-member:
  # %player%
  message: "&c[YouTube] &bNew Member &d%player% &ahas just subscribed!"
  sound:
    name: "entity.player.levelup"
    volume: 1.0
    pitch: 1.5
  # --- NEW: Boss Bar Settings ---
  boss-bar:
    enabled: true
    # %player%
    message: "&c[YouTube] &d&lWelcome to our new member, &f&l%player%&d&l!"
    color: "PINK"
    duration: 10

# --- Super Sticker ---
super-sticker:
  # %player% = Username
  # %amount% = Amount
  message: "&c[YouTube] &e%player% &fhas Super Sticker sent worth &a%amount%&f!"
  sound:
    name: "entity.villager.celebrate"
    volume: 1.0
    pitch: 1.2
  boss-bar:
    enabled: true
    # %player%, %amount%
    message: "&c[YouTube] &a&l%player% &f&lsent a Super Sticker!"
    color: "GREEN"
    duration: 10

# --- Gifted Membership ---
gifted-membership:
  # %gifter% = Gifter's name
  # %amount% = Number of gifts (usually 1)
  message: "&c[YouTube] &f%gifter% &ehas gifted a membership!"
  sound:
    name: "entity.player.levelup"
    volume: 1.0
    pitch: 1.8
  boss-bar:
    enabled: true
    # %gifter%
    message: "&c[YouTube] &d&l%gifter% &f&lhas gifted a membership!"
    color: "PURPLE"
    duration: 12

member-milestone:
  enabled: true
  # %player% = Username
  # %milestone% = Message from YouTube (e.g., "1 Year", "2 Months")
  # %message% = The message the viewer sent along with it
  message: "&a[Milestone!] &e%player% &fhas been a member for &d%milestone%&f! Message: &d%message%"
  sound:
    name: "entity.ender_dragon.growl"
    volume: 1.0
    pitch: 1.5
  boss-bar:
    enabled: true
    # %player%, %milestone%
    message: "&a&lMember Milestone! &f&l%player% (%milestone%)"
    color: "GREEN"
    duration: 15